### PR TITLE
Anna

### PR DESCRIPTION
**Pull request by AnnaDorogaya**
Need help to put all items in one row and do color only for container (not for the whole screen)

### CODE REVIEW

**Comment by sshenis** [comment]
Hi Anna, 

To put everything in one row, you need to put "flexDirection: row" on the **overall container** . 
So like 
<View style={{flexDirection: row}}>
<Image />
<Text></Text>
<Text></Text>
</View>

To do only color for the container, you need to have a bigger view outside your component:
**<View>**
<View style={{flexDirection: row, backgroundColor: #FAD}}>
<Image />
<Text></Text>
<Text></Text>
</View>
**</View>**

**Comment by sshenis** [comment]
Screen Shot 2019-12-11 at 10 34 30 AM

**Comment by AnnaDorogaya** [comment]
Thank you Shenis. It worked. Now my text and omega in the row, but text is more on the top and not in the middle, where is picture. How can I move text down?

**Comment by AnnaDorogaya** [comment]
*picture, not omega

**Comment by sshenis** [comment]
justifyContent: 'center' >>>> Centers your text horizontally
alignItems: 'center' >>>> Centers your text vertically.

Use justify Content

**Comment by sshenis** [comment]
Anna looking at your code, I want you to do the following.

Screen Shot 2019-12-11 at 10 49 06 AM

**Comment by AnnaDorogaya** [comment]
Thank you! It helped.

**Comment by Jaydankai** [comment]
Hi Anna - Testing

**Comment by Jaydankai** [comment]
I see that your tasks for the animation #5 is for Opacity

**Comment by Jaydankai** [comment]
so in your Style for the <View>, make sure you set your style for Opacity to whatever you animation name is (in your case I think is "fadeAnim"

**Comment by Jaydankai** [comment]
I just found out that you are trying to animate the TouchableOpacity, not the View. So what you need to do now is to move your Animate quote to the Touchable Opacity

**Comment by Jaydankai** [comment]
and don't forget to delete the Animate at the end of the View Quote

**Comment by AnnaDorogaya** [comment]
Thank you Jaydan, but it still doesn't work :(

**Pull request merged**
