### PR TITLE
Corinti

### PR DESCRIPTION
**Pull request by Jeanos**
Please Need Help on Animation

### CODE REVIEW

**Comment by Jaydankai** [comment]
hi Jack - Testing

**Comment by Jaydankai** [comment]
I see that you are trying to animate both width and height of your View section
what I would do is make two separate consts, one for "width" and one for "Height"=

**Comment by Jaydankai** [comment]
then on your "Style" property, add your width and height const to their style sections

**Comment by Jaydankai** [comment]
let me know how it goes

**Comment by Jeanos** [comment]
Hey sshenis Thanks for your Help. I was using Image instead of Animated.Image.

**Pull request closed without merging**
